lib/coin_portfolio_web/router.ex
defmodule CoinPortfolioWeb.Router do
  use CoinPortfolioWeb, :router

  import CoinPortfolioWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_root_layout, {CoinPortfolioWeb.LayoutView, :root}
    plug CoinPortfolioWeb.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CoinPortfolioWeb do
    pipe_through :browser

    # get "/", PageController, :index
    live "/", IndexLive, :indexo
  end

  # Other scopes may use custom stacks.
  scope "/api", CoinPortfolioWeb do
    pipe_through :api

    get "/rates", RatesController, :rates
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CoinPortfolioWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", CoinPortfolioWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CoinPortfolioWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", CoinPortfolioWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/coin_portfolio_web/views/layout_view.ex
defmodule CoinPortfolioWeb.LayoutView do
  use CoinPortfolioWeb, :view
end

lib/coin_portfolio_web/templates/layout/_user_menu.html.eex
<div class="ui top fixed inverted gradient text menu mb-0">
  <div class="header item">
    <img src="<%= Routes.static_path(@conn, "/images/logo.png") %>" /> &nbsp;
    <a href="/"> Coin Portfolio</a>
  </div>
  <div class="menu right">
    <%= if @current_user do %>
      <div class="ui simple dropdown item">
        <a class="item"><i class="large user circle icon"></i> <%=@current_user.name%></a>
        <i class="dropdown icon"></i>
        <div class="menu">
          <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "item" %>
          <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "item" %>
        </div>
      </div>
    <% else %>
      <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "item" %>
      <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "item" %>
    <% end %>
  </div>
</div>

lib/coin_portfolio_web/templates/layout/app.html.eex
<div class="ui fluid container">
<%= @inner_content %>
</div>

lib/coin_portfolio_web/templates/layout/live.html.leex
<div class="ui fluid container">
    <%= @inner_content %>
</div>

lib/coin_portfolio_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CoinPortfolio · Keep track of your token spends and earnings</title>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <%= csrf_meta_tag() %>
    <link rel="stylesheet" type="text/css" href="<%= Routes.static_path(@conn, "/semantic/dist/semantic.min.css") %>">
    <script src="<%= Routes.static_path(@conn, "/semantic/dist/semantic.min.js") %>"></script>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="manifest" href="manifest.json">
    <script type="module">
      // This is the "Offline copy of pages" service worker
      /*
      This code uses the pwa-update web component https://github.com/pwa-builder/pwa-update to register your service worker,
      tell the user when there is an update available and let the user know when your PWA is ready to use offline.
      */

      import 'https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate';

      const el = document.createElement('pwa-update');
      document.body.appendChild(el);
    </script>
  </head>
  <body>
    <%= render "_user_menu.html", assigns %>
    <main role="main" class="main">
      <%= if get_flash(@conn, :info) do %>
        <p class="ui info message" role="alert"><i class="close icon"></i> <%= get_flash(@conn, :info) %></p>
      <%end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="ui negative message" role="alert"><i class="close icon"></i> <%= get_flash(@conn, :error) %></p>
      <%end %>
      <%= @inner_content %>
    </main>
    <script defer>
      $('.message .close')
      .on('click', function() {
        $(this)
          .closest('.message')
          .transition('fade');
      });
    </script>
  </body>
</html>